name: ${project.name}
description: ${project.description}
version: ${project.version}
main: com.rngservers.irondoors.Main
api-version: 1.13
author: RandomUnknown

permissions:
  irondoors.use:
    default: true
    description: Open iron doors with hand