name: ${project.name}
description: ${project.description}
version: ${project.version}
main: com.ranull.irondoors.IronDoors
author: Ranull

permissions:
  irondoors.use:
    default: true
    description: Open iron doors and trap doors with hand