name: ${project.name}
description: ${project.description}
version: ${project.version}
main: com.ranull.irondoors.IronDoors
author: Ranull
api-version: 1.19

permissions:
  irondoors.irondoor:
    default: true
    description: Open iron doors with your hand
  irondoors.irontrapdoor:
    default: true
    description: Open iron trap doors with your hand
