name: IronDoors
main: com.rngservers.irondoors.Main
description: Open iron doors with hand
version: 1.1
api-version: 1.13
author: RandomUnknown

permissions:
  irondoors.use:
    default: true
    description: Open iron doors with hand